spring:
  profiles:
    active:
      - jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/config_server
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    bus:
      destination: jaejoon-topic
    config:
      monitor:
        endpoint:
          path: /api/v1/remote-config
      enabled: true
      server:
        jdbc:
          sql: select property_key, property_value from remote_properties where application=? and profile=? and label=?
  kafka:
    bootstrap-servers: http://localhost:9092
